### ISSUE TITLE
Support more bookmark and history formats

### ISSUE THREAD

**Issue by kopischke** [kopischke/alfred-workflows#1]
This issue is a placeholder for additional bookmark and history file support in the _Now and Then (the web)_ extension. If you wish to see more formats added, please attach a bookmark and / or history file to a comment stating what application uses it and where it is usually stored on a OS X system.

Please note the extension is a file filter, so only metadata files indexed by Spotlight can be integrated. If the browser or application you wish to see supported does not store bookmark and / or history information in metadata files, or if these are in a format that is not indexed by Spotlight, do not comment on this issue.

**Comment by a-x-** [comment]
firefox

https://github.com/nikipore/alfred-firefoxbookmarks/issues/new

**Comment by kopischke** [comment]
@a-x- sorry for only now getting to comment on this. As you may have surmised from the lack of updates these past years, I have stopped using Alfred, or any launcher for that matter; I’ve found that the most recent macOS versions’ Spotlight does enough for 90 % of my needs, and that I‘d rather forfeit the last 10 % than go down another rabbit hole of installing, configuring and maintaining plugins. 

This means I am not going to follow up on your nudge from my and, but, as you seem to be interested in merging the workflows: would you like to take over ownership for _Now and Then_ (and any other other of my Alfred plugins that strikes your fancy, for that matter)?
