### ISSUE TITLE
Outdated Google translate workflow 

### ISSUE THREAD

**Issue by g0to** [kopischke/alfred-workflows#2]
Any plans on updating the workflow to work with the new Google API?

Thanks a million for your work! :)

**Comment by kopischke** [comment]
Seeing the Translate API is [a paid service](https://cloud.google.com/translate/docs?csw=1), I don’t think so – unless you are meaning something else by “the new Google API”. I must admit I haven’t used the workflow lately, as I’m mostly away from my Mac, so I’ll have to ask: has the current version stopped working?

**Comment by g0to** [comment]
Yep. The workflow stopped working a few days ago. :(

Please take a look at the posts from April 8th onwards here:

http://www.alfredforum.com/topic/120-google-translate-workflow/page-2

On Tue, Apr 14, 2015 at 10:53 AM, Martin Kopischke <notifications@github.com

**Comment by kopischke** [comment]
OK, that is annoying. I will see what I can do about a workaround, but I can’t give you an ETA on that, being a bit lacking in the free time department ATM.

**Comment by g0to** [comment]
That's totally fine. Thanks so much for taking a look, Martin and also
thanks one more time for the super helpful workflow ;)

On Tue, Apr 14, 2015 at 12:54 PM, Martin Kopischke <notifications@github.com

**Comment by kopischke** [comment]
Fixed in 58b9e5f8cf1c55bc6ce1ef8058bc57e8de3f7809.

**Comment by g0to** [comment]
That was amazingly fast! Thanks a ton! ;)

I hope your free time department would get more time resources in a near future. 

Take care!

**Comment by kopischke** [comment]
Thanks :). Shawn Rice had laid it all out already, all I still had to do was get that into a tidy form… let me know if any other issue (or even the same one, fingers crossed) pops up.

**Comment by bonka** [comment]
I don't know if I did anything wrong, but my version only returns the first word of the sentence. I tried deleting the workflow and reinstalling it, same result. I must be doing something wrong…
![kopischke-alfred-workflows-query](https://cloud.githubusercontent.com/assets/1240278/7157380/97a00f8e-e36f-11e4-81ac-68662725a257.png)
![kopischke-alfred-workflows-paste](https://cloud.githubusercontent.com/assets/1240278/7157383/9b6dff40-e36f-11e4-8225-41cb772cc5df.png)
</center>

Deanishe on Alfredforums also made a [modification](http://www.alfredforum.com/topic/120-google-translate-workflow/?p=35081) to the original to allow sentences with periods in them. Are periods accounted for in this version?

BTW: _Awwesome_ workflow. Use it all the time, thanks a bunch for sharing/fixing!

**Comment by kopischke** [comment]
> I don't know if I did anything wrong, but my version only returns the first word of the sentence. I tried deleting the workflow and reinstalling it, same result. I must be doing something wrong…

I’ll test as soon as I am back at my Mac, but most probably I messed up the shell escaping while refactoring. Should be an easy fix, but would you mind opening a new issue for it?

> Deanishe on Alfredforums also made a modification to the original to allow sentences with periods in them. Are periods accounted for in this version?

Nope: I made no functional changes to the workflow, just fixed the retrieval of results from Google (minus whatever I messed up for multi word terms). Dean’s patch makes liberal use of Python, and I don’t want to use an external interpreter as that would significantly slow down the workflow, especially on less beefy machines (right now, lookup is almost instant, and I would very much like to keep it that way). I might investigate ways to add multi-sentence support purely in `bash`, but I’m a bit pressed for time ATM, so don’t hold your breath for it. Sorry.

**Comment by kopischke** [comment]
Regression issue opened at #3.
