### ISSUE TITLE
Current version of Google Translate workflow only translates first word of the argument

### ISSUE THREAD

**Issue by g0to** [kopischke/alfred-workflows#3]
I think the name of the issue says it all.

Thanks a ton, kopischke! :)

**Comment by kopischke** [comment]
@g0to fixed in most recent commit. Even worse stupidity on my side than I first assumed, but an easy fix indeed; thanks for reporting!

**Comment by g0to** [comment]
Awesome! Thanks a lot once again for doing it so quickly! ;)

**Comment by kopischke** [comment]
You are very welcome. I’m glad to see the workflows have their users, and I’ll try to keep them functional for as long as I use Alfred (at least those that are not deprecated by the Cupertino based steam roller – the Tagger one can probably go, by now ;)).
