### ISSUE TITLE
No translation found

### ISSUE THREAD

**Issue by malinni4** [kopischke/alfred-workflows#4]
Debug log

``` xml
[STDERR: alfred.workflow.input.scriptfilter] ./translate: line 2: warning: setlocale: LC_ALL: cannot change locale (en_GB@currency=UAH.UTF-8): No such file or directory
[INFO: alfred.workflow.input.scriptfilter] <?xml version="1.0" encoding="UTF-8"?><items>
  <item uid="translation" arg="No translation found!">
    <title><![CDATA[No translation found!]]></title>
    <icon>icon.png</icon>
    <subtitle>”h” in English.</subtitle>
  </item>
</items>
[STDERR: alfred.workflow.input.scriptfilter] ./translate: line 2: warning: setlocale: LC_ALL: cannot change locale (en_GB@currency=UAH.UTF-8): No such file or directory
[INFO: alfred.workflow.input.scriptfilter] <?xml version="1.0" encoding="UTF-8"?><items>
  <item uid="translation" arg="No translation found!">
    <title><![CDATA[No translation found!]]></title>
    <icon>icon.png</icon>
    <subtitle>”h” in German.</subtitle>
  </item>
</items>
[STDERR: alfred.workflow.input.scriptfilter] ./translate: line 2: warning: setlocale: LC_ALL: cannot change locale (en_GB@currency=UAH.UTF-8): No such file or directory
[INFO: alfred.workflow.input.scriptfilter] <?xml version="1.0" encoding="UTF-8"?><items>
  <item uid="translation" arg="No translation found!">
    <title><![CDATA[No translation found!]]></title>
    <icon>icon.png</icon>
    <subtitle>”h” in French.</subtitle>
  </item>
</items>
[STDERR: alfred.workflow.input.scriptfilter] ./translate: line 2: warning: setlocale: LC_ALL: cannot change locale (en_GB@currency=UAH.UTF-8): No such file or directory
[INFO: alfred.workflow.input.scriptfilter] <?xml version="1.0" encoding="UTF-8"?><items>
  <item uid="translation" arg="No translation found!">
    <title><![CDATA[No translation found!]]></title>
    <icon>icon.png</icon>
    <subtitle>”hello” in English.</subtitle>
  </item>
</items>
[STDERR: alfred.workflow.input.scriptfilter] ./translate: line 2: warning: setlocale: LC_ALL: cannot change locale (en_GB@currency=UAH.UTF-8): No such file or directory
[INFO: alfred.workflow.input.scriptfilter] <?xml version="1.0" encoding="UTF-8"?><items>
  <item uid="translation" arg="No translation found!">
    <title><![CDATA[No translation found!]]></title>
    <icon>icon.png</icon>
    <subtitle>”hello” in German.</subtitle>
  </item>
</items>
[STDERR: alfred.workflow.input.scriptfilter] ./translate: line 2: warning: setlocale: LC_ALL: cannot change locale (en_GB@currency=UAH.UTF-8): No such file or directory
[INFO: alfred.workflow.input.scriptfilter] <?xml version="1.0" encoding="UTF-8"?><items>
  <item uid="translation" arg="No translation found!">
    <title><![CDATA[No translation found!]]></title>
    <icon>icon.png</icon>
    <subtitle>”hello” in French.</subtitle>
  </item>
</items>
```

**Comment by kopischke** [comment]
It seems the script parses an odd value of `en_GB@currency=UAH.UTF-8` out of your locale settings, causing an invalid script locale to be set and the whole thing to fail. I’m on holiday right now and have a rather busy few weeks coming up after that, but I’ll get back to you as soon as I can.

**Comment by malinni4** [comment]
Thank you!

**Comment by malinni4** [comment]
Thank you! 
FYI, i get rid of that message with a locale fail but still negative result

Starting debug for 'Google Translate'

[INFO: alfred.workflow.input.scriptfilter] <?xml version="1.0" encoding="UTF-8"?>

<![CDATA[No translation found!]]>
icon.png
”h” in German.


[INFO: alfred.workflow.input.scriptfilter] <?xml version="1.0" encoding="UTF-8"?>

<![CDATA[No translation found!]]>
icon.png
”h” in English.


[INFO: alfred.workflow.input.scriptfilter] <?xml version="1.0" encoding="UTF-8"?>

<![CDATA[No translation found!]]>
icon.png
”h” in French.


[INFO: alfred.workflow.input.scriptfilter] <?xml version="1.0" encoding="UTF-8"?>

<![CDATA[No translation found!]]>
icon.png
”hi” in German.


[INFO: alfred.workflow.input.scriptfilter] <?xml version="1.0" encoding="UTF-8"?>

<![CDATA[No translation found!]]>
icon.png
”hi” in French.


[INFO: alfred.workflow.input.scriptfilter] <?xml version="1.0" encoding="UTF-8"?>

<![CDATA[No translation found!]]>
icon.png
”hi” in English.

**Comment by malinni4** [comment]
Thank you! 
FYI, i get rid of that message with a locale fail but still negative result

Starting debug for 'Google Translate'

[INFO: alfred.workflow.input.scriptfilter] <?xml version="1.0" encoding="UTF-8"?><items>
  <item uid="translation" arg="No translation found!">
	<title><![CDATA[No translation found!]]></title>
	<icon>icon.png</icon>
	<subtitle>”h” in German.</subtitle>
  </item>
</items>
[INFO: alfred.workflow.input.scriptfilter] <?xml version="1.0" encoding="UTF-8"?><items>
  <item uid="translation" arg="No translation found!">
	<title><![CDATA[No translation found!]]></title>
	<icon>icon.png</icon>
	<subtitle>”h” in English.</subtitle>
  </item>
</items>
[INFO: alfred.workflow.input.scriptfilter] <?xml version="1.0" encoding="UTF-8"?><items>
  <item uid="translation" arg="No translation found!">
	<title><![CDATA[No translation found!]]></title>
	<icon>icon.png</icon>
	<subtitle>”h” in French.</subtitle>
  </item>
</items>
[INFO: alfred.workflow.input.scriptfilter] <?xml version="1.0" encoding="UTF-8"?><items>
  <item uid="translation" arg="No translation found!">
	<title><![CDATA[No translation found!]]></title>
	<icon>icon.png</icon>
	<subtitle>”hi” in German.</subtitle>
  </item>
</items>
[INFO: alfred.workflow.input.scriptfilter] <?xml version="1.0" encoding="UTF-8"?><items>
  <item uid="translation" arg="No translation found!">
	<title><![CDATA[No translation found!]]></title>
	<icon>icon.png</icon>
	<subtitle>”hi” in French.</subtitle>
  </item>
</items>
[INFO: alfred.workflow.input.scriptfilter] <?xml version="1.0" encoding="UTF-8"?><items>
  <item uid="translation" arg="No translation found!">
	<title><![CDATA[No translation found!]]></title>
	<icon>icon.png</icon>
	<subtitle>”hi” in English.</subtitle>
  </item>
</items>
[INFO: alfred.workflow.input.scriptfilter] <?xml version="1.0" encoding="UTF-8"?><items>
  <item uid="translation" arg="No translation found!">
	<title><![CDATA[No translation found!]]></title>
	<icon>icon.png</icon>
	<subtitle>”r” in English.</subtitle>
  </item>
</items>
[INFO: alfred.workflow.input.scriptfilter] <?xml version="1.0" encoding="UTF-8"?><items>
  <item uid="translation" arg="No translation found!">
	<title><![CDATA[No translation found!]]></title>
	<icon>icon.png</icon>
	<subtitle>”r” in German.</subtitle>
  </item>
</items>
[INFO: alfred.workflow.input.scriptfilter] <?xml version="1.0" encoding="UTF-8"?><items>
  <item uid="translation" arg="No translation found!">
	<title><![CDATA[No translation found!]]></title>
	<icon>icon.png</icon>
	<subtitle>”r” in French.</subtitle>
  </item>
</items>
[INFO: alfred.workflow.input.scriptfilter] <?xml version="1.0" encoding="UTF-8"?><items>
  <item uid="translation" arg="No translation found!">
	<title><![CDATA[No translation found!]]></title>
	<icon>icon.png</icon>
	<subtitle>”rid ” in German.</subtitle>
  </item>
</items>
[INFO: alfred.workflow.input.scriptfilter] <?xml version="1.0" encoding="UTF-8"?><items>
  <item uid="translation" arg="No translation found!">
	<title><![CDATA[No translation found!]]></title>
	<icon>icon.png</icon>
	<subtitle>”rid ” in English.</subtitle>
  </item>
</items>
[INFO: alfred.workflow.input.scriptfilter] <?xml version="1.0" encoding="UTF-8"?><items>
  <item uid="translation" arg="No translation found!">
	<title><![CDATA[No translation found!]]></title>
	<icon>icon.png</icon>
	<subtitle>”rid ” in French.</subtitle>
  </item>
</items>

**Comment by malinni4** [comment]
Thanks! FYI, I get rid of previous message but still result is negative

``` xml
[INFO: alfred.workflow.input.scriptfilter] <?xml version="1.0" encoding="UTF-8"?><items>
  <item uid="translation" arg="No translation found!">
    <title><![CDATA[No translation found!]]></title>
    <icon>icon.png</icon>
    <subtitle>”h” in French.</subtitle>
  </item>
</items>
[INFO: alfred.workflow.input.scriptfilter] <?xml version="1.0" encoding="UTF-8"?><items>
  <item uid="translation" arg="No translation found!">
    <title><![CDATA[No translation found!]]></title>
    <icon>icon.png</icon>
    <subtitle>”h” in English.</subtitle>
  </item>
</items>
[INFO: alfred.workflow.input.scriptfilter] <?xml version="1.0" encoding="UTF-8"?><items>
  <item uid="translation" arg="No translation found!">
    <title><![CDATA[No translation found!]]></title>
    <icon>icon.png</icon>
    <subtitle>”h” in German.</subtitle>
  </item>
</items>
[INFO: alfred.workflow.input.scriptfilter] <?xml version="1.0" encoding="UTF-8"?><items>
  <item uid="translation" arg="No translation found!">
    <title><![CDATA[No translation found!]]></title>
    <icon>icon.png</icon>
    <subtitle>”hi” in French.</subtitle>
  </item>
</items>
[INFO: alfred.workflow.input.scriptfilter] <?xml version="1.0" encoding="UTF-8"?><items>
  <item uid="translation" arg="No translation found!">
    <title><![CDATA[No translation found!]]></title>
    <icon>icon.png</icon>
    <subtitle>”hi” in English.</subtitle>
  </item>
</items>
[INFO: alfred.workflow.input.scriptfilter] <?xml version="1.0" encoding="UTF-8"?><items>
  <item uid="translation" arg="No translation found!">
    <title><![CDATA[No translation found!]]></title>
    <icon>icon.png</icon>
    <subtitle>”hi” in German.</subtitle>
  </item>
</items>
```

**Comment by malinni4** [comment]
I figure out that in the morning it works for a couple of time and after something blocking the IP address. Then I changing IP address (VPN let's say) it will work again for a couple of times and after another IP will be blocked.

**Comment by kopischke** [comment]
That sound as if Google has started rate limiting requests. Newer versions of Alfred have an option to only start a query when typing ends (in the workflow settings); could you check what happens when you activate that on a “clean” IP?

**Comment by malinni4** [comment]
I tried it, still the same. Limit is about 5 to 10 request from one IP (I tried a couple of IP's), also I tried to remove one language and the number of available requests increased.

**Comment by g0to** [comment]
@kopischke, any updates about what could be the issue? I'm having the same problem as @malinni4 with exact repro steps.

Thanks!

**Comment by kopischke** [comment]
Sorry for the inconvenience, but RL is keeping me away from my Mac for a while, so I have no way to debug this. I’ll look into this as soon as I can get back to my machine.

**Comment by g0to** [comment]
That's not a problem! Just wanted to know if there were any updates.

Thanks again for taking a look and no rush at all!

**Comment by OmarKN** [comment]
Hi and good day,

Same problem here - on Yosemite - 
I see "Translate to German" f ex then:
"No translation found."

/
with best regards,
Omar KN
Stockholm, Sweden

**Comment by kopischke** [comment]
Thanks a lot for reporting, and apologies for not reacting, but the workflows published here are, as far as I am concerned, deprecated: I haven’t been using Alfred since macOS revamped Spotlight, which is good enough for me, especially as my main work machine is an iPad by now. I will archive the repo, no fixes planned.
